### ISSUE TITLE
zero flag handling

### ISSUE THREAD

**Issue by PalatinCoder** [PalatinCoder/PIC-Simulator#1]
wann muss das zero flag wieder resettet werden?

see c76e11b

**Comment by d-Rickyy-b** [comment]
Aktuelle Lösung ist das ZeroFlag immer dann zu "resetten", wenn eine Operation, die das Z-Bit setzt, **nicht** 0 ergibt.

Ich werde mal per Mail nachhaken, ob das richtig ist, oder ob wir etwas vergessen haben.
