### ISSUE TITLE
DC fehlerhaft implementiert

### ISSUE THREAD

**Issue by PalatinCoder** [PalatinCoder/PIC-Simulator#10]
Testprogramm1 setzt bei Zeile 29 `addlw 25h` DC = 1
Lehmann tut's nicht. Hä?

**Comment by d-Rickyy-b** [comment]
@PalatinCoder Lehmann's PIC ist fehlerhaft implementiert, soweit ich das richtig in Erinnerung habe.

**Comment by PalatinCoder** [comment]
@d-Rickyy-b OMG :see_no_evil:
