### ISSUE TITLE
Alle Tests grün

### ISSUE THREAD

**Issue by d-Rickyy-b** [PalatinCoder/PIC-Simulator#17]
- [x] Test 1 - Literal Befehle
- [x] Test 2 - CALL, GOTO, RETLW, RETURN geprüft
- [x] Test 3 - File-Register Befehle
- [x] Test 4 - DECFSZ, INCFSZ, RLF, RRF 
- [x] Test 5 - BCF, BSF, BTFSC und BTFSS
- [x] Test 6 - indirekte Adressierung
- [x] Test 7 - Timer0 mit und ohne Vorteiler
- [x] Test 8 - Interrupts für TMR0, RB0 (INT) und RB4-7
- [x] Test 9 - SLEEP-Befehl
- [x] Test 10 - Funktionsweise von PCL und PCLATH
- [x] Test 11 - Watchdog mit und ohne Vorteiler
- [x] Test 12 - Beschreiben und Lesen des EEPROMs

**Comment by PalatinCoder** [comment]
Test 9 Sleep läuft zwar, allerdings stimmt die Zeit net. Lehmann fragen (weil Watchdog period = 18ms, wieso sollte das Programm also 2,3ms schlafen?!)

**Comment by PalatinCoder** [comment]
Test 11: Ist der Reset richtig?

**Comment by d-Rickyy-b** [comment]
DC handling neu bearbeiten

**Comment by d-Rickyy-b** [comment]
Problem mit DC handling gefixt.
Test 9 - Fehler mit WDT behoben

**Comment by d-Rickyy-b** [comment]
Test 11 ist grün, wenn Frequenz = 4 MHz
