### ISSUE TITLE
Program Counter in Speicher (0x02) integrieren

### ISSUE THREAD

**Issue by d-Rickyy-b** [PalatinCoder/PIC-Simulator#3]
Die unteren 8 Bits des Program Counters sitzen an Adresse 0x02 im Speicher. Dort sollten sie später (in der UI) auch angezeigt werden bzw. von Programmen verändert werden können.

**Comment by PalatinCoder** [comment]
Dann muss das ganze raus aus dem Prozessor rein in den memory controller.

Wo gondeln die oberen 8 bit rum?

**Comment by d-Rickyy-b** [comment]
@PalatinCoder "The upper bits of the PC are loaded from PCLATH" (Adresse 0x0A).

Ich kümmere mich drum :)

**Comment by d-Rickyy-b** [comment]
Ist gefixt
