### ISSUE TITLE
TrisA und TrisB in I/O Ansicht werden nicht aktualisiert, bei Veränderung

### ISSUE THREAD

**Issue by d-Rickyy-b** [PalatinCoder/PIC-Simulator#34]
Da scheint das Binding irgendwie nicht zu klappen. Fehlen Getter/Setter?

**Comment by PalatinCoder** [comment]
Vermutlich nur bei Veränderung durch das Programm. Welcher Test?

**Comment by PalatinCoder** [comment]
fixed in 7cf7c6e
