### ISSUE TITLE
Prescaler und WDT implementieren

### ISSUE THREAD

**Issue by d-Rickyy-b** [PalatinCoder/PIC-Simulator#5]
> When assigned to the Timer0 module, all instructions writing to the TMR0 register (e.g., CLRF 1, MOVWF 1, BSF 1,etc.) will clear the prescaler. When assigned to WDT, a CLRWDT instruction will clear the prescaler along with the WDT. 

Der TMR0 wird vom Befehlstakt incrementiert. beim Überlauf wird ein Interrupt ausgelöst

**Comment by PalatinCoder** [comment]
Prescaler für Timer0 ist drin

**Comment by PalatinCoder** [comment]
Sollte stimmen, im Großen und Ganzen (siehe Notiz in #17 )
